# Generated by Django 4.2.1 on 2023-07-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_facture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
