# Generated by Django 4.2.2 on 2023-07-17 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='type',
            field=models.CharField(blank=True, choices=[('C', 'Client'), ('F', 'Fournisseur')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.provider'),
        ),
    ]
