# Generated by Django 4.2.1 on 2023-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_facture_type_alter_facture_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='raison_sociale',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='provider',
            name='ville',
            field=models.CharField(default='', max_length=50),
        ),
    ]
