# Generated by Django 4.2.1 on 2023-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_provider_raison_sociale_provider_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='degree',
        ),
        migrations.AddField(
            model_name='client',
            name='OD',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='OG',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='benificiaire',
            field=models.CharField(default='', max_length=50),
        ),
    ]
