# Generated by Django 4.2.1 on 2023-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_client_degree_client_od_client_og_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='reference',
            field=models.CharField(default='', max_length=500),
        ),
    ]
