# Generated by Django 4.2.1 on 2023-07-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_facture_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='fix',
            field=models.CharField(default='', max_length=50),
        ),
    ]
