# Generated by Django 4.2.1 on 2023-07-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_provider_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='reste_du_montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
