# Generated by Django 4.2.1 on 2023-07-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_facture_avance_facture_reste_du_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='avance',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='reste_du_montant',
        ),
    ]
