# Generated by Django 4.2.1 on 2023-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_facture_avance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ADD',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='EIP',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='monture',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='verre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
