# Generated by Django 4.2.1 on 2023-07-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_client_add_client_eip_client_monture_client_verre'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='categorie',
            field=models.CharField(default='', max_length=500),
        ),
    ]
