# Generated by Django 4.2.1 on 2023-07-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_stock_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
